version: "3.5"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    volumes:
      - mysql:/data/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    volumes:
      - phpmyadmin:/root/.phpmyadmin
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - mysql

#  server:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#    image: tsed/typeorm:latest
#    container_name: server_container
#    restart: always
#    environment:
#    env_file:
#      - ./env/.env.local
#    depends_on:
#      - mysql
#    ports:
#      - "9000:9000"
#    stdin_open: true # -i
#    tty: true # -t
#    networks:
#      - mysql

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
  phpmyadmin:
