version: 2
description: "Node CI/CD (Heroku)"

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:dubnium

jobs:
  checkout-scm:
    <<: *defaults
    name: Checkout
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths: .
  lint-and-build:
    <<: *defaults
    name: Build & Lint
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - v1-modules-{{ checksum "package.json" }}
            - v1-modules-
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          name: Save NPM Package Cache
          key: v1-modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
  docker-build-release:
    name: Docker Build & Release
    working_directory: ~/repo
    machine: true
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=${$CIRCLE_SHA1 | cut -c -7}' >> $BASH_ENV
            echo 'export IMAGE_NAME=dressit' >> $BASH_ENV
      - run:
          name: Build and Push Docker Image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t omerico/$IMAGE_NAME:$TAG .
            docker push omerico/$IMAGE_NAME:$TAG
      #        - run:
      #            name: Publish Github Version
      #            command: |
      #              git tag latest -f
      #              git push -f --tags --no-verify
      - run:
          name: Deploy To DigitalOcean
          command: echo 'Deploy'
      - persist_to_workspace:
          root: ~/repo
          paths: .

workflows:
  version: 2
  test-deploy:
    jobs:
      - checkout-scm:
          context: bingetime
      - lint-and-build:
          context: bingetime
          requires:
            - checkout-scm
      - docker-build-release:
          context: bingetime
          requires:
            - checkout-scm
            - lint-and-build
          filters:
            branches:
              only:
                - master
